### ISSUE TITLE
Intermittent timing issue when renewing bound certificates

### ISSUE THREAD

**Issue by leefine02** [Keyfactor/gcp-loadbalancer-orchestrator#9]
On rare occasions when renewing a bound certificate in GCP, the previous step to remove bindings is not completely done before the next API call attempts to delete the alias causing an error.  The status of the previous API call needs to be checked to make sure it is finished before moving on to the next step.

**Comment by fiddlermikey** [comment]
fixed in https://github.com/Keyfactor/gcp-loadbalancer-orchestrator/pull/10
